name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync-fork:
    name: Sync Fork with Upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "Your Name"
          git remote add upstream https://github.com/roothide/bootstrap
          git fetch upstream
          git checkout main
          git merge upstream/main

  build:
    name: Build Bootstrap
    runs-on: macos-latest
    needs: sync-fork

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Make Bootstrap Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap.tipa
          path: ./packages/Bootstrap.tipa

  update-release:
    name: Release .tipa
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: Bootstrap.tipa
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: Beta Release
          body: These are automatically updated builds of the latest commit.
          artifacts: "Bootstrap.tipa"
          tag: release
          token: ${{ secrets.GITHUB_TOKEN }}
